torrent_update_metadata_job:
  every: '5s'
  class: TorrentUpdateMetadataJob
  queue: high
  description: >
    update torrents metadata

verify_cancel_torrent_job:
  every: '5s'
  class: VerifyCancelTorrentJob
  queue: high
  description: >
    verify downloads torrent
